services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: relatorio_servico_db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
volumes:
  data:
